version: "3"

networks:
  quacker:
    driver: bridge

services:
  # quacker
  quacker:
    build:
      context: .
    environment:
      QUACKER_HOST: "rabbitmq.host.com"
      QUACKER_PORT: "5672"
      QUACKER_USERNAME: "rabbitmq-username"
      QUACKER_PASSWORD: "rabbitmq-password"
      QUACKER_EXCHANGE: "default"
      QUACKER_TOPIC: "your-topic"
      QUACKER_CLIENTID: "rabbitmq-quacker"
      QUACKER_INTERVAL: "1000"
      QUACKER_DATAFILE: "/data.json"
    volumes:
      - ./data.json:/data.json
    networks:
      - quacker
